import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { parseDate, statusBucket, isOverdue, calculateMetrics } from '../dist/assets/shared.js';
import { filterData, emptyFilters, validateActions, sortRecords, flattenRecords } from '../dist/assets/filters.js';
import { buildReport } from '../dist/assets/report-model.js';
import { createReportPdf } from '../src/pdf.js';
import { reserveBudget, LIMITS, estimateUpperBound } from '../netlify/functions/_shared/budget.mjs';
import { handleAI, buildMessages } from '../netlify/functions/_shared/ai-service.mjs';
import { parseGviz } from '../netlify/functions/_shared/google-sheets.mjs';
import { transformWorkbook, containsSensitiveAbsenceFields } from '../netlify/functions/_shared/data.mjs';
const demo=JSON.parse(await readFile(new URL('../dist/data/demo-data.json',import.meta.url),'utf8'));
function store(){let state=null,version=0;return{getWithMetadata:async()=>state?{data:structuredClone(state),etag:String(version)}:null,setJSON:async(_k,data,c)=>{if(c.onlyIfNew&&state||c.onlyIfMatch&&c.onlyIfMatch!==String(version))return{modified:false};state=structuredClone(data);version++;return{modified:true};}};}
test('datas inválidas não passam e status negado/cancelado não resolve nem vence',()=>{assert.equal(parseDate('31/02/2026'),null);assert.equal(parseDate('12/13/2026'),null);assert.equal(statusBucket('Não concluída'),'open');assert.equal(statusBucket('OK'),'resolved');assert.equal(isOverdue({due:'2020-01-01',status:'Cancelada'}),false);assert.equal(isOverdue({due:'2026-09-10',status:'Aberta'},new Date('2026-09-11T01:00:00Z')),false);});
test('filtro multimês exclui sem data; filtros são combinados sem inventar campos',()=>{const data={...demo,inspections:[...demo.inspections,{sector:'Produção'}]};assert.equal(filterData(data,{months:['2026-08','2026-09']}).inspections.length,6);assert.equal(filterData(data,{months:['undated']}).inspections.length,1);assert.equal(filterData(data,{sector:'Produção',status:'progress'}).inspections.length,1);assert.equal(filterData(data,{status:'open'}).dds.length,0);assert.equal(filterData(data,{registered:'yes'}).dds.length,3);});
test('pendências não são somadas às inspeções para taxa e atrasos',()=>{const m=calculateMetrics(demo);assert.equal(m.actions,2);assert.equal(m.resolved,0);assert.equal(calculateMetrics({}).resolutionRate,null);});
test('mapeia o cabeçalho real da planilha e não interpreta incidente como CID',()=>{const result=transformWorkbook({pending:[{'Não conformidade / problema':'Incidente na área',Data:'01/09/2026',Prazo:'01/10/2026'}]});assert.equal(result.pending[0].description,'Incidente na área');assert.deepEqual(result.months,['2026-09']);assert.equal(containsSensitiveAbsenceFields(result),false);assert.equal(containsSensitiveAbsenceFields({absences:[{CID:'X'}]}),true);});
test('GViz interpreta datas entre aspas e não altera texto contendo Date()',()=>{const value={table:{cols:[{label:'Data'},{label:'Texto'}],rows:[{c:[{v:'Date(2026,8,11)'},{v:'A expressão Date(2026,8,11)'}]}]}};assert.deepEqual(parseGviz(JSON.stringify(value)),[{Data:'2026-09-11',Texto:'A expressão Date(2026,8,11)'}]);});
test('relatórios usam a data de registro, nunca o prazo para duplicar meses',()=>{const data={...demo,pending:[{date:'2026-08-31',due:'2026-09-11'}]};const r=buildReport(data,{type:'monthly',date:'2026-09',filters:emptyFilters(),notes:'Texto revisado'});assert.equal(r.data.pending.length,0);assert.equal(r.notes,'Texto revisado');assert.equal(r.filters.start,'2026-09-01');const week=buildReport(data,{type:'weekly',date:'2026-09-09'});assert.equal(week.filters.start,'2026-09-07');assert.equal(week.filters.end,'2026-09-13');});
test('explorador mantém todos os registros e ordena por data',()=>{const rows=sortRecords(flattenRecords(demo),'date-asc');assert.equal(rows.length,14);assert.equal(rows[0].recordDate,'2026-08-12');});
test('ações da IA têm lista permitida; não executa JS, URLs ou gravação remota',()=>{assert.deepEqual(validateActions([{type:'eval',code:'alert(1)'},{type:'delete'},{type:'set_theme',theme:'dark'}]),[{type:'set_theme',theme:'dark'}]);});
test('cota atômica aceita apenas uma das chamadas concorrentes',async()=>{const ledger=store();const result=await Promise.allSettled(Array.from({length:15},()=>reserveBudget(ledger,5000,Date.parse('2026-09-11T12:00:00Z'))));assert.equal(result.filter(x=>x.status==='fulfilled').length,1);});
test('cota diária, intervalo na virada do dia e rejeição de entrada excessiva',async()=>{const ledger=store(),start=Date.parse('2026-09-11T23:59:30Z');await reserveBudget(ledger,6000,start);await assert.rejects(reserveBudget(ledger,6000,start+40000),/intervalo/);await assert.rejects(reserveBudget(ledger,6001,start+65000),/grande/);const next=await reserveBudget(ledger,6000,start+65000);assert.equal(next.remainingTokens,54000);for(let i=1;i<10;i++)await reserveBudget(ledger,6000,start+65000*(i+1));await assert.rejects(reserveBudget(ledger,1,start+65000*12),/diária/);});
test('mensagem típica de IA cabe no limite conservador',()=>{const messages=buildMessages({mode:'dashboard',question:'Mostre as pendências vencidas',filters:{}},demo);assert.ok(estimateUpperBound(messages,1100)<=LIMITS.perCall, String(estimateUpperBound(messages,1100)));});
test('PDF com mais de 40 inspeções mantém o último registro e notas',()=>{const data={...demo,inspections:Array.from({length:65},(_,i)=>({...demo.inspections[2],condition:`Registro completo ${i+1}`}))};const r=buildReport(data,{type:'monthly',date:'2026-09',demo:true,notes:'Conclusão revisada preservada'});const doc=createReportPdf(r);assert.ok(doc.getNumberOfPages()>2);assert.equal(r.data.inspections.length,65);assert.ok(doc.output('arraybuffer').byteLength>3000);});
test('IA separa chaves, usa dados confiáveis e não chama Groq sem cota',async()=>{
  const previous=[process.env.GROQ_DASHBOARD_API_KEY,process.env.GROQ_REPORT_API_KEY];process.env.GROQ_DASHBOARD_API_KEY='test-dashboard';process.env.GROQ_REPORT_API_KEY='test-report';let calls=0;
  const upstream=async(_url,init)=>{calls++;assert.equal(init.headers.Authorization,'Bearer test-dashboard');const sent=JSON.parse(init.body);assert.ok(!JSON.stringify(sent).includes('SEGREDO_CLIENTE'));return Response.json({choices:[{message:{content:JSON.stringify({answer:'Dados lidos',actions:[{type:'eval'}]})}}],usage:{total_tokens:120}});};
  const req=()=>new Request('https://example.netlify.app/api/ia',{method:'POST',headers:{origin:'https://example.netlify.app','Content-Type':'application/json'},body:JSON.stringify({mode:'dashboard',question:'Resumo?',context:{secret:'SEGREDO_CLIENTE'}})});
  try{const denied=await handleAI(req(),{snapshot:async()=>demo,upstream});assert.equal(denied.status,503);assert.equal(calls,0);const ok=await handleAI(req(),{store:store(),snapshot:async()=>demo,upstream});assert.equal(ok.status,200);assert.deepEqual((await ok.json()).actions,[]);assert.equal(calls,1);}finally{for(const [i,key]of ['GROQ_DASHBOARD_API_KEY','GROQ_REPORT_API_KEY'].entries())previous[i]===undefined?delete process.env[key]:process.env[key]=previous[i];}
});
